changelog:
  categories:
    - title: Breaking Changes 🛠
      labels:
        - "breaking change"
    - title: New Features 🎉
      labels:
        - enhancement
    - title: Bug Fixes 🪲
      labels:
        - bug
    - title: Performance Improvements 🏎️
      labels:
        - performance
    - title: Dependency Updates
      labels:
        - dependencies
    - title: Other Changes
      labels:
        - "*"
