services:
  redis:
    # this service is only needed if you are using the Redis cache with Cache__Type=Redis
    image: redis:alpine
    ports:
    - "6379:6379"

  simplecdn:
    image: ${DOCKER_REGISTRY-}simplecdn:local-dev
    build:
      context: .
      dockerfile: SimpleCDN/Dockerfile
    volumes:
    - ../:/data
    ports:
    - "1780:8080"
    environment:
    - CDN_DATA_ROOT=/data
    - ASPNETCORE_ENVIRONMENT=Development
    - Cache__Redis__ConnectionString=redis:6379 # Only needed if Cache__Type=Redis
    - Cache__Type=Redis # Redis, InMemory, or Disabled
