services:
  simplecdn:
    image: ${DOCKER_REGISTRY-}simplecdn:local-dev
    build:
      context: .
      dockerfile: SimpleCDN/Dockerfile
    volumes:
    - ../:/data
    environment:
    - CDN_DATA_ROOT=/data
    - RedisCache__User=redis
    - RedisCache__Password=secret_redis