services:
  simplecdn:
    image: ${DOCKER_REGISTRY-}simplecdn:local-dev
    build:
      context: .
      dockerfile: SimpleCDN/Dockerfile
      # args:
      # - VERSION_NUMBER=1.0.0
      # - VERSION_SUFFIX=rc1
    volumes:
    - ../:/data
    environment:
    - CDN_DATA_ROOT=/data