services:
  redis:
    # this service is only needed if you are using the Redis cache with Cache__Type=Redis
    image: redis:alpine
    ports:
    - "6379:6379" # Expose Redis on the host machine so it can be accessed by for example a dashboard

  simplecdn:
    image: ghcr.io/jonathanbout/simplecdn:local-dev
    build:
      context: .
      dockerfile: src/standalone/Dockerfile
    volumes:
    - ../:/data
    ports:
    - "1780:8080"
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    - Cache__Redis__ConnectionString=redis:6379 # Only needed if Cache__Type=Redis
    - Cache__Type=InMemory # Redis, InMemory, or Disabled
