name: Cleanup
on:
  delete:
  workflow_dispatch:

jobs:
  cleanup:
    if: github.event.ref_type == 'branch'
    runs-on: ubuntu-24.04
    steps:
      - name: Branch Caches
        run: |
          echo "Fetching list of cache key"
          cacheKeysForPR=$(gh cache list --ref $BRANCH --limit 100 --json id --jq '.[].id')

          ## Setting this to not fail the workflow while deleting cache keys.
          set +e
          echo "Deleting caches..."
          for cacheKey in $cacheKeysForPR
          do
              gh cache delete $cacheKey
          done
          echo "Done"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          BRANCH: ${{ github.event.ref }}
