# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Tests

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'

jobs:
  unit-test:
    runs-on: ubuntu-latest
    name: Unit Tests
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          9.0.x
          8.0.x
    - name: Restore dependencies
      run: dotnet restore tests/unit/SimpleCDN.Tests.Unit.csproj
    - name: Build
      run: dotnet build tests/unit/SimpleCDN.Tests.Unit.csproj --no-restore -p:TreatWarningsAsErrors=true
    - name: Test
      run: dotnet test tests/unit/SimpleCDN.Tests.Unit.csproj --no-build --verbosity normal -p:TreatWarningsAsErrors=true

  integration-test:
    runs-on: ubuntu-latest
    name: Integration Tests
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore tests/integration/SimpleCDN.Tests.Integration.csproj
    - name: Build
      run: dotnet build tests/integration/SimpleCDN.Tests.Integration.csproj --no-restore
    - name: Test
      run: dotnet test tests/integration/SimpleCDN.Tests.Integration.csproj --no-build --verbosity normal
