# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Tests

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'

jobs:
  unit-test:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref_name }}-unit-tests
      cancel-in-progress: true
    runs-on: ubuntu-24.04
    name: Unit Tests
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          9.0.x
          8.0.x
    - name: Restore dependencies
      run: dotnet restore tests/unit/SimpleCDN.Tests.Unit.csproj
    - name: Build
      run: dotnet build -c Release tests/unit/SimpleCDN.Tests.Unit.csproj --no-restore -p:TreatWarningsAsErrors=true
    - name: Test
      run: dotnet test -c Release tests/unit/SimpleCDN.Tests.Unit.csproj --no-build --verbosity normal -p:TreatWarningsAsErrors=true

  integration-test:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref_name }}-integration-tests
      cancel-in-progress: true
    runs-on: ubuntu-24.04
    name: Integration Tests
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore tests/integration/SimpleCDN.Tests.Integration.csproj
    - name: Build
      run: dotnet build -c Release tests/integration/SimpleCDN.Tests.Integration.csproj --no-restore
    - name: Test
      run: dotnet test -c Release tests/integration/SimpleCDN.Tests.Integration.csproj --no-build --verbosity normal
